from ironmatrix.data.database import db
from ironmatrix.data.models import Exercise

def seed_database():
    exercises = [
        {'name': 'Barbell Bench Press', 'type': 'Barbell', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 3, 'chest': 10, 'back': 1, 'shoulders': 4, 'biceps': 1, 'triceps': 6, 'core': 3},
        {'name': 'Incline Bench Press', 'type': 'Barbell', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 3, 'chest': 9, 'back': 1, 'shoulders': 6, 'biceps': 1, 'triceps': 6, 'core': 3},
        {'name': 'Dumbbell Flyes', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 2, 'chest': 10, 'shoulders': 2, 'triceps': 1, 'core': 2},
        {'name': 'Push-ups', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 5, 'chest': 8, 'back': 1, 'shoulders': 4, 'biceps': 1, 'triceps': 6, 'core': 4},
        {'name': 'Pull-ups/Chin-ups', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 6, 'chest': 2, 'back': 9, 'shoulders': 4, 'biceps': 7, 'triceps': 2, 'core': 5},
        {'name': 'Barbell Rows', 'type': 'Barbell', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 4, 'chest': 2, 'back': 9, 'shoulders': 6, 'biceps': 6, 'triceps': 1, 'core': 5},
        {'name': 'Lat Pulldowns', 'type': 'Cable', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 3, 'chest': 1, 'back': 9, 'shoulders': 4, 'biceps': 6, 'triceps': 1, 'core': 4},
        {'name': 'Inverted Rows', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 5, 'chest': 2, 'back': 8, 'shoulders': 5, 'biceps': 5, 'triceps': 2, 'core': 4},
        {'name': 'Superman', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 3, 'chest': 1, 'back': 7, 'shoulders': 3, 'biceps': 1, 'triceps': 1, 'quads': 1, 'hamstrings': 6, 'glutes': 6, 'core': 6},
        {'name': 'Overhead Press', 'type': 'Barbell', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 4, 'chest': 3, 'back': 3, 'shoulders': 10, 'biceps': 1, 'triceps': 5, 'quads': 1, 'glutes': 2, 'calves': 1, 'core': 6},
        {'name': 'Lateral Raises', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 2, 'chest': 1, 'back': 1, 'shoulders': 9, 'triceps': 1, 'core': 2},
        {'name': 'Handstand Push-ups', 'type': 'Bodyweight', 'difficulty': 3, 'compound_score': 7, 'metabolic_score': 7, 'chest': 4, 'back': 2, 'shoulders': 9, 'biceps': 1, 'triceps': 6, 'core': 6},
        {'name': 'Rear Delt Flyes', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 3, 'metabolic_score': 2, 'chest': 1, 'back': 4, 'shoulders': 8, 'biceps': 1, 'triceps': 1, 'core': 2},
        {'name': 'Pike Push-ups', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 5, 'chest': 3, 'back': 1, 'shoulders': 8, 'biceps': 1, 'triceps': 5, 'core': 4},
        {'name': 'Bicep Curls', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 1, 'metabolic_score': 1, 'chest': 1, 'back': 2, 'shoulders': 1, 'biceps': 10, 'core': 2},
        {'name': 'Hammer Curls', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 1, 'metabolic_score': 1, 'chest': 1, 'back': 2, 'shoulders': 2, 'biceps': 8, 'triceps': 1, 'core': 2},
        {'name': 'Tricep Extensions', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 1, 'metabolic_score': 1, 'chest': 1, 'back': 1, 'shoulders': 2, 'triceps': 10, 'core': 2},
        {'name': 'Close-Grip Bench Press', 'type': 'Barbell', 'difficulty': 1, 'compound_score': 4, 'metabolic_score': 3, 'chest': 6, 'back': 1, 'shoulders': 3, 'biceps': 1, 'triceps': 9, 'core': 3},
        {'name': 'Dips', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 5, 'chest': 7, 'back': 1, 'shoulders': 4, 'biceps': 1, 'triceps': 8, 'core': 3},
        {'name': 'Barbell Squats', 'type': 'Barbell', 'difficulty': 3, 'compound_score': 9, 'metabolic_score': 6, 'back': 4, 'shoulders': 2, 'biceps': 1, 'triceps': 1, 'quads': 10, 'hamstrings': 4, 'glutes': 8, 'calves': 2, 'core': 6},
        {'name': 'Leg Extensions', 'type': 'Machine', 'difficulty': 1, 'compound_score': 1, 'metabolic_score': 2, 'quads': 10, 'glutes': 1, 'core': 1},
        {'name': 'Front Squats', 'type': 'Barbell', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 6, 'back': 3, 'shoulders': 3, 'biceps': 1, 'triceps': 1, 'quads': 9, 'hamstrings': 3, 'glutes': 7, 'calves': 2, 'core': 8},
        {'name': 'Leg Press', 'type': 'Machine', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 3, 'back': 1, 'quads': 9, 'hamstrings': 3, 'glutes': 7, 'calves': 1, 'core': 2},
        {'name': 'Pistol Squats', 'type': 'Bodyweight', 'difficulty': 3, 'compound_score': 8, 'metabolic_score': 7, 'back': 2, 'shoulders': 1, 'biceps': 1, 'triceps': 1, 'quads': 9, 'hamstrings': 4, 'glutes': 7, 'calves': 3, 'core': 7},
        {'name': 'Wall Sits', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 4, 'back': 1, 'quads': 8, 'hamstrings': 3, 'glutes': 6, 'calves': 1, 'core': 4},
        {'name': 'Jump Squats', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 8, 'back': 2, 'shoulders': 2, 'biceps': 1, 'triceps': 1, 'quads': 8, 'hamstrings': 4, 'glutes': 7, 'calves': 5, 'core': 5},
        {'name': 'Romanian Deadlifts', 'type': 'Barbell', 'difficulty': 3, 'compound_score': 9, 'metabolic_score': 5, 'back': 6, 'shoulders': 2, 'biceps': 2, 'triceps': 1, 'quads': 2, 'hamstrings': 10, 'glutes': 8, 'calves': 1, 'core': 6},
        {'name': 'Leg Curls', 'type': 'Machine', 'difficulty': 1, 'compound_score': 1, 'metabolic_score': 2, 'quads': 1, 'hamstrings': 10, 'glutes': 2, 'core': 1},
        {'name': 'Deadlifts', 'type': 'Barbell', 'difficulty': 3, 'compound_score': 10, 'metabolic_score': 7, 'chest': 1, 'back': 8, 'shoulders': 3, 'biceps': 3, 'triceps': 2, 'quads': 6, 'hamstrings': 9, 'glutes': 8, 'calves': 2, 'core': 7},
        {'name': 'Hip Thrusts', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 3, 'back': 1, 'quads': 2, 'hamstrings': 6, 'glutes': 10, 'core': 4},
        {'name': 'Glute Bridges', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 4, 'metabolic_score': 2, 'back': 1, 'quads': 1, 'hamstrings': 5, 'glutes': 9, 'core': 4},
        {'name': 'Lunges', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 6, 'back': 2, 'shoulders': 1, 'quads': 8, 'hamstrings': 6, 'glutes': 9, 'calves': 1, 'core': 5},
        {'name': 'Step-ups', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 6, 'back': 1, 'shoulders': 1, 'quads': 7, 'hamstrings': 5, 'glutes': 8, 'calves': 4, 'core': 3},
        {'name': 'Calf Raises', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 1, 'metabolic_score': 2, 'quads': 1, 'hamstrings': 1, 'glutes': 2, 'calves': 10, 'core': 1},
        {'name': 'Planks', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 3, 'metabolic_score': 3, 'chest': 1, 'back': 2, 'shoulders': 2, 'biceps': 1, 'triceps': 2, 'quads': 1, 'hamstrings': 1, 'glutes': 3, 'core': 10},
        {'name': 'Crunches', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 1, 'metabolic_score': 3, 'core': 9},
        {'name': 'Russian Twists', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 4, 'back': 1, 'shoulders': 1, 'biceps': 1, 'triceps': 1, 'quads': 1, 'glutes': 1, 'core': 9},
        {'name': 'Side Planks', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 3, 'metabolic_score': 3, 'chest': 1, 'back': 2, 'shoulders': 2, 'biceps': 1, 'triceps': 2, 'quads': 1, 'hamstrings': 1, 'glutes': 3, 'core': 9},
        {'name': 'Mountain Climbers', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 9, 'chest': 2, 'back': 1, 'shoulders': 3, 'biceps': 1, 'triceps': 3, 'quads': 5, 'hamstrings': 2, 'glutes': 4, 'calves': 2, 'core': 8},
        {'name': 'Bear Crawls', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 8, 'chest': 3, 'back': 3, 'shoulders': 4, 'biceps': 2, 'triceps': 4, 'quads': 4, 'hamstrings': 2, 'glutes': 4, 'calves': 1, 'core': 8},
        {'name': 'Burpees', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 9, 'metabolic_score': 10, 'chest': 5, 'back': 2, 'shoulders': 5, 'biceps': 2, 'triceps': 5, 'quads': 6, 'hamstrings': 3, 'glutes': 5, 'calves': 3, 'core': 7},
        {'name': 'Dumbbell Chest Press', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 3, 'chest': 10, 'back': 1, 'shoulders': 3, 'biceps': 1, 'triceps': 6, 'core': 3},
        {'name': 'Dumbbell Pullovers', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 4, 'metabolic_score': 3, 'chest': 8, 'back': 6, 'shoulders': 2, 'biceps': 1, 'triceps': 2, 'core': 4},
        {'name': 'Dumbbell Shoulder Press', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 3, 'chest': 2, 'back': 2, 'shoulders': 9, 'biceps': 1, 'triceps': 5, 'quads': 1, 'core': 5},
        {'name': 'Dumbbell Shrugs', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 1, 'chest': 1, 'back': 8, 'shoulders': 7, 'biceps': 1, 'triceps': 1, 'core': 2},
        {'name': 'Single-Arm Dumbbell Rows', 'type': 'Dumbbell', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 4, 'chest': 1, 'back': 9, 'shoulders': 5, 'biceps': 6, 'triceps': 2, 'core': 5},
        {'name': 'Dumbbell Deadlifts', 'type': 'Dumbbell', 'difficulty': 3, 'compound_score': 9, 'metabolic_score': 6, 'chest': 1, 'back': 7, 'shoulders': 2, 'biceps': 3, 'triceps': 2, 'quads': 5, 'hamstrings': 8, 'glutes': 7, 'calves': 2, 'core': 6},
        {'name': 'Dumbbell Thrusters', 'type': 'Dumbbell', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 9, 'chest': 3, 'back': 4, 'shoulders': 8, 'biceps': 2, 'triceps': 6, 'quads': 6, 'hamstrings': 4, 'glutes': 6, 'calves': 2, 'core': 6},
        {'name': 'Goblet Squats', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 5, 'chest': 1, 'back': 3, 'shoulders': 3, 'biceps': 2, 'triceps': 2, 'quads': 9, 'hamstrings': 3, 'glutes': 7, 'calves': 1, 'core': 5},
        {'name': 'Bulgarian Split Squats', 'type': 'Dumbbell', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 6, 'back': 2, 'shoulders': 1, 'biceps': 1, 'triceps': 1, 'quads': 8, 'hamstrings': 5, 'glutes': 8, 'calves': 2, 'core': 5},
        {'name': 'Dumbbell Arnold Press', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 4, 'chest': 2, 'back': 3, 'shoulders': 9, 'biceps': 2, 'triceps': 5, 'quads': 1, 'core': 5},
        {'name': 'Dumbbell Upright Rows', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 3, 'chest': 2, 'back': 6, 'shoulders': 7, 'biceps': 5, 'triceps': 2, 'core': 3},
        {'name': 'Dumbbell Tricep Kickbacks', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 1, 'chest': 1, 'back': 2, 'shoulders': 3, 'biceps': 1, 'triceps': 9, 'core': 2},
        {'name': 'Dumbbell Skull Crushers', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 3, 'metabolic_score': 2, 'chest': 2, 'back': 1, 'shoulders': 3, 'biceps': 1, 'triceps': 9, 'core': 3},
        {'name': 'Farmers Walk', 'type': 'Dumbbell', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 7, 'chest': 2, 'back': 4, 'shoulders': 4, 'biceps': 4, 'triceps': 4, 'quads': 3, 'hamstrings': 2, 'glutes': 4, 'calves': 6, 'core': 6},
        {'name': 'Dumbbell Renegade Rows', 'type': 'Dumbbell', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 8, 'chest': 4, 'back': 8, 'shoulders': 4, 'biceps': 5, 'triceps': 4, 'glutes': 2, 'core': 8},
        {'name': 'Turkish Get-ups', 'type': 'Dumbbell', 'difficulty': 3, 'compound_score': 9, 'metabolic_score': 8, 'chest': 3, 'back': 4, 'shoulders': 6, 'biceps': 3, 'triceps': 4, 'quads': 5, 'hamstrings': 3, 'glutes': 5, 'calves': 2, 'core': 8},
        {'name': 'Dumbbell Bent-over Rows', 'type': 'Dumbbell', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 4, 'chest': 2, 'back': 8, 'shoulders': 5, 'biceps': 6, 'triceps': 2, 'core': 5},
        {'name': 'Cable Chest Fly', 'type': 'Cable', 'difficulty': 1, 'compound_score': 3, 'metabolic_score': 3, 'chest': 9, 'shoulders': 2, 'triceps': 2, 'core': 2},
        {'name': 'Cable Crossover', 'type': 'Cable', 'difficulty': 1, 'compound_score': 4, 'metabolic_score': 4, 'chest': 9, 'shoulders': 3, 'triceps': 2, 'core': 2},
        {'name': 'Cable Lateral Raise', 'type': 'Cable', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 2, 'shoulders': 9, 'core': 1},
        {'name': 'Cable Face Pull', 'type': 'Cable', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 4, 'back': 5, 'shoulders': 7, 'biceps': 3, 'triceps': 2, 'core': 3},
        {'name': 'Cable Triceps Pushdown', 'type': 'Cable', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 3, 'shoulders': 1, 'triceps': 10, 'core': 1},
        {'name': 'Cable Bicep Curl', 'type': 'Cable', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 3, 'shoulders': 1, 'biceps': 10, 'core': 1},
        {'name': 'Cable Rope Hammer Curl', 'type': 'Cable', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 3, 'shoulders': 1, 'biceps': 9, 'triceps': 1, 'core': 1},
        {'name': 'Cable Pull-through', 'type': 'Cable', 'difficulty': 1, 'compound_score': 6, 'metabolic_score': 5, 'back': 2, 'shoulders': 1, 'triceps': 1, 'quads': 2, 'hamstrings': 6, 'glutes': 10, 'core': 4},
        {'name': 'Cable Squat to Row', 'type': 'Cable', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 7, 'back': 7, 'shoulders': 5, 'biceps': 2, 'triceps': 3, 'quads': 8, 'hamstrings': 4, 'glutes': 6, 'calves': 1, 'core': 6},
        {'name': 'Dips', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 5, 'chest': 3, 'back': 1, 'shoulders': 5, 'biceps': 1, 'triceps': 8, 'core': 3},
        {'name': 'Bodyweight Squats', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 6, 'shoulders': 1, 'triceps': 1, 'quads': 9, 'hamstrings': 2, 'glutes': 3, 'calves': 1, 'core': 2},
        {'name': 'Burpees', 'type': 'Bodyweight', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 10, 'chest': 4, 'back': 3, 'shoulders': 5, 'biceps': 2, 'triceps': 3, 'quads': 6, 'hamstrings': 3, 'glutes': 3, 'calves': 2, 'core': 6},
        {'name': 'Mountain Climbers', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 5, 'metabolic_score': 9, 'chest': 1, 'back': 1, 'shoulders': 3, 'biceps': 1, 'triceps': 1, 'quads': 5, 'hamstrings': 2, 'glutes': 2, 'calves': 1, 'core': 8},
        {'name': 'Plank', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 2, 'metabolic_score': 4, 'shoulders': 2, 'core': 10},
        {'name': 'Wall Sit', 'type': 'Bodyweight', 'difficulty': 1, 'compound_score': 3, 'metabolic_score': 6, 'quads': 8, 'hamstrings': 2, 'glutes': 2, 'core': 4},
        {'name': 'Barbell Deadlift', 'type': 'Barbell', 'difficulty': 3, 'compound_score': 10, 'metabolic_score': 6, 'back': 9, 'shoulders': 3, 'biceps': 2, 'triceps': 2, 'quads': 6, 'hamstrings': 9, 'glutes': 9, 'calves': 1, 'core': 6},
        {'name': 'Barbell Front Squat', 'type': 'Barbell', 'difficulty': 3, 'compound_score': 9, 'metabolic_score': 6, 'back': 1, 'shoulders': 5, 'biceps': 1, 'triceps': 2, 'quads': 10, 'hamstrings': 4, 'glutes': 5, 'calves': 1, 'core': 5},
        {'name': 'Clean and Press', 'type': 'Barbell', 'difficulty': 3, 'compound_score': 10, 'metabolic_score': 9, 'chest': 3, 'back': 6, 'shoulders': 9, 'biceps': 3, 'triceps': 4, 'quads': 7, 'hamstrings': 6, 'glutes': 6, 'calves': 2, 'core': 7},
        {'name': 'Barbell Overhead Press', 'type': 'Barbell', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 4, 'chest': 1, 'shoulders': 10, 'biceps': 1, 'triceps': 6, 'core': 3},
        {'name': 'Kettlebell Swing', 'type': 'Kettlebell', 'difficulty': 2, 'compound_score': 7, 'metabolic_score': 8, 'back': 2, 'shoulders': 2, 'triceps': 1, 'quads': 3, 'hamstrings': 7, 'glutes': 10, 'calves': 1, 'core': 5},
        {'name': 'Trap Bar Deadlift', 'type': 'Barbell', 'difficulty': 3, 'compound_score': 9, 'metabolic_score': 6, 'back': 8, 'shoulders': 2, 'biceps': 1, 'triceps': 2, 'quads': 8, 'hamstrings': 7, 'glutes': 9, 'calves': 1, 'core': 5},
        {'name': 'Atlas Stone Lift', 'type': 'Strongman', 'difficulty': 3, 'compound_score': 10, 'metabolic_score': 7, 'chest': 4, 'back': 6, 'shoulders': 5, 'biceps': 3, 'triceps': 5, 'quads': 9, 'hamstrings': 8, 'glutes': 10, 'calves': 2, 'core': 6},
        {'name': 'Yoke Carry', 'type': 'Strongman', 'difficulty': 3, 'compound_score': 9, 'metabolic_score': 9, 'chest': 1, 'back': 3, 'shoulders': 4, 'biceps': 1, 'triceps': 3, 'quads': 8, 'hamstrings': 7, 'glutes': 9, 'calves': 2, 'core': 9},
        {'name': 'Farmer\'s Walk', 'type': 'Strongman', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 9, 'back': 4, 'shoulders': 4, 'biceps': 2, 'triceps': 4, 'quads': 6, 'hamstrings': 4, 'glutes': 5, 'calves': 5, 'core': 8},
        {'name': 'Log Press', 'type': 'Strongman', 'difficulty': 2, 'compound_score': 8, 'metabolic_score': 7, 'chest': 3, 'back': 1, 'shoulders': 9, 'biceps': 1, 'triceps': 7, 'quads': 2, 'hamstrings': 1, 'glutes': 1, 'core': 4},
        {'name': 'Tire Flip', 'type': 'Strongman', 'difficulty': 3, 'compound_score': 10, 'metabolic_score': 8, 'chest': 4, 'back': 5, 'shoulders': 5, 'biceps': 2, 'triceps': 3, 'quads': 7, 'hamstrings': 6, 'glutes': 7, 'calves': 2, 'core': 6}
    ]

    db.connect()
    for ex_data in exercises:
        Exercise.create(**ex_data)
    db.close()

if __name__ == "__main__":
    seed_database()
    print(f"Database seeded with {len(exercises)} exercises from CSV data.")
